export enum TripStatus {
    // ON_ROUTE = 'ON_ROUTE',
    ARRIVED = 'ARRIVED',
    CANCELLED = 'CANCELLED',
    PENDING_CONFIRMATION = 'PENDING_CONFIRMATION',
    COMPLETED = 'COMPLETED',
    REJECTED = 'REJECTED',
}